import type { Category, Challenge, SubCategory } from "../types/challenge";

export const CATEGORIES: Category[] = [
  {
    id: "coding",
    name: "Coding",
    icon: "code-slash",
    color: "#3B82F6",
    gradient: ["#60A5FA", "#3B82F6"],
    description: "Writing, reading, and reasoning about code",
    subCategories: [
      {
        id: "debugging",
        name: "Debugging",
        parentCategory: "coding",
        description: "Find and fix errors in complex systems.",
        icon: "bug",
        color: "#EF4444",
        gradient: ["#F87171", "#EF4444"],
        type: "theory",
      },
      {
        id: "rest-api",
        name: "REST API Design",
        parentCategory: "coding",
        description: "Build scalable and secure APIs.",
        icon: "cloud-upload",
        color: "#3B82F6",
        gradient: ["#60A5FA", "#3B82F6"],
        type: "practical",
      },
    ],
  },
  {
    id: "cyber",
    name: "Cyber Security",
    icon: "shield-half",
    color: "#6366F1",
    gradient: ["#818CF8", "#6366F1"],
    description: "Infrastructure and encryption safety",
    subCategories: [
      {
        id: "cryptography",
        name: "Cryptography",
        parentCategory: "cyber",
        description: "Implementation of encryption protocols.",
        icon: "lock-closed",
        color: "#6366F1",
        gradient: ["#818CF8", "#6366F1"],
        type: "theory",
      },
      {
        id: "penetration",
        name: "Penetration Testing",
        parentCategory: "cyber",
        description: "Ethical hacking and assessment.",
        icon: "terminal",
        color: "#111827",
        gradient: ["#374151", "#111827"],
        type: "practical",
      },
    ],
  },
  {
    id: "math",
    name: "Mathematics",
    icon: "calculator",
    color: "#10B981",
    gradient: ["#34D399", "#10B981"],
    description: "Foundations for tech excellence",
    subCategories: [
      {
        id: "discrete-math",
        name: "Discrete Math",
        parentCategory: "math",
        description: "Logic, sets, and graph theory.",
        icon: "infinite",
        color: "#10B981",
        gradient: ["#34D399", "#10B981"],
        type: "theory",
      },
      {
        id: "calc-viz",
        name: "Calculus Visualization",
        parentCategory: "math",
        description: "Understanding rates of change.",
        icon: "analytics",
        color: "#F59E0B",
        gradient: ["#FBBF24", "#F59E0B"],
        type: "theory",
      },
    ],
  },
  {
    id: "algorithms",
    name: "Algorithms",
    icon: "git-branch",
    color: "#8B5CF6",
    gradient: ["#A78BFA", "#8B5CF6"],
    description: "Structured thinking and efficiency",
    subCategories: [
      {
        id: "searching",
        name: "Searching",
        parentCategory: "algorithms",
        description: "Master efficient data retrieval.",
        icon: "search",
        color: "#8B5CF6",
        gradient: ["#A78BFA", "#8B5CF6"],
        type: "theory",
      },
      {
        id: "dynamic-prog",
        name: "Dynamic Programming",
        parentCategory: "algorithms",
        description: "Optimize recursive problems.",
        icon: "layers",
        color: "#F43F5E",
        gradient: ["#FB7185", "#F43F5E"],
        type: "practical",
      },
    ],
  },
  {
    id: "logic",
    name: "Logic",
    icon: "bulb",
    color: "#06B6D4",
    gradient: ["#22D3EE", "#06B6D4"],
    description: "Pure reasoning power",
    subCategories: [
      {
        id: "deduction",
        name: "Deduction",
        parentCategory: "logic",
        description: "Conclusion from constraints.",
        icon: "help-buoy",
        color: "#06B6D4",
        gradient: ["#22D3EE", "#06B6D4"],
        type: "theory",
      },
    ],
  },
];

// Mock challenge data
export const MOCK_CHALLENGES: Challenge[] = [
  {
    id: "1",
    title: "Fix the Login Bug",
    description: "Debug a broken authentication flow",
    category: "coding",
    subCategory: "debugging",
    difficulty: "beginner",
    rating: 4.5,
    estimatedTime: 15,
    xpReward: 50,
  },
  {
    id: "2",
    title: "Binary Search Master",
    description: "Implement an efficient search algorithm",
    category: "algorithms",
    subCategory: "searching",
    difficulty: "intermediate",
    rating: 4.7,
    estimatedTime: 20,
    xpReward: 75,
  },
  {
    id: "3",
    title: "Design a Chat System",
    description: "Architect a scalable messaging platform",
    category: "system-design",
    subCategory: "architecture",
    difficulty: "advanced",
    rating: 4.9,
    estimatedTime: 45,
    xpReward: 150,
  },
  {
    id: "4",
    title: "Logic Grid Puzzle",
    description: "Solve a complex deduction challenge",
    category: "logic",
    subCategory: "reasoning",
    difficulty: "beginner",
    rating: 4.3,
    estimatedTime: 10,
    xpReward: 30,
  },
  {
    id: "5",
    title: "Server Outage Response",
    description: "Debug a production system failure",
    category: "real-world",
    subCategory: "debugging-live",
    difficulty: "advanced",
    rating: 4.8,
    estimatedTime: 30,
    xpReward: 120,
  },
  {
    id: "6",
    title: "Optimize Database Query",
    description: "Improve slow query performance",
    category: "coding",
    subCategory: "optimization",
    difficulty: "intermediate",
    rating: 4.6,
    estimatedTime: 25,
    xpReward: 80,
  },
  {
    id: "7",
    title: "Graph Traversal",
    description: "Navigate complex data structures",
    category: "algorithms",
    subCategory: "graphs",
    difficulty: "intermediate",
    rating: 4.5,
    estimatedTime: 20,
    xpReward: 70,
  },
  {
    id: "8",
    title: "API Rate Limiting",
    description: "Design a scalable rate limiter",
    category: "system-design",
    subCategory: "api-design",
    difficulty: "advanced",
    rating: 4.7,
    estimatedTime: 35,
    xpReward: 130,
  },
  {
    id: "9",
    title: "Pattern Matching",
    description: "Identify hidden sequences",
    category: "logic",
    subCategory: "patterns",
    difficulty: "beginner",
    rating: 4.4,
    estimatedTime: 12,
    xpReward: 40,
  },
];

export const SUB_CATEGORIES_DATA: SubCategory[] = CATEGORIES.flatMap(
  (cat) => cat.subCategories,
);
